<?php

$PUB90="cellphonebeatcom_instapress_cms";
$PUB20="alwaysfoodiecom_instapress_cms";
$PUB508="audiovideoclancom_instapress_cms";
$PUB111="awesomeasiacom_instapress_cms";
$PUB38="beacheszonecom_instapress_cms";
$PUB24="bodyartclancom_instapress_cms";
$PUB139="borntechiecom_instapress_cms";
$PUB502="diyhealthcom_instapress_cms";
$PUB97="europeeuphoriacom_instapress_cms";
$PUB121="fitnessqncom_instapress_cms";
$PUB19="gardeningclancom_instapress_cms";
$PUB70="greencarsclancom_instapress_cms";
$PUB137="homeqncom_instapress_cms";
$PUB507="honeymoonbeatcom_instapress_cms";
$PUB506="hotelsbeatcom_instapress_cms";
$PUB22="kitchenclancom_instapress_cms";
$PUB118="madaboutyachtscom_instapress_cms";
$PUB39="onedollartripcom_instapress_cms";
$PUB44="parentingclancom_instapress_cms";
$PUB16="petsclancom_instapress_cms";
$PUB509="plumbingdailycom_instapress_cms";
$PUB62="beautyrampcom_instapress_cms";
$PUB34="thefatproblemcom_instapress_cms";
$PUB26="weddingclancom_instapress_cms";
$PUB5="yourbizourbizcom_instapress_cms";
$PUB10="gizmowatchcom_instapress_cms";
$PUB153='automottocom_instapress_cms';
$PUB150='stylegurucom_instapress_cms';
$PUB149='bornrichcom_instapress_cms ';
?>
